#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [[ -f "$ENV_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$ENV_FILE"
fi

COUNT="${JIBRI_COUNT:-10}"
OUTPUT="${SCRIPT_DIR}/jibri-pool.yml"

cat > "$OUTPUT" <<EOF
# Auto-generated by generate-jibri-pool.sh
# JIBRI_COUNT=${COUNT}
# Regenerate: ./generate-jibri-pool.sh

services:
EOF

for i in $(seq 1 "$COUNT"); do
    CONFIG_DIR="${CONFIG}/jibri-${i}"
    mkdir -p "$CONFIG_DIR" 2>/dev/null || true
    cat >> "$OUTPUT" <<EOS
  jibri-${i}:
    image: jitsi/jibri:\${JITSI_IMAGE_VERSION:-unstable}
    restart: \${RESTART_POLICY:-unless-stopped}
    shm_size: '2gb'
    cap_add:
      - SYS_ADMIN
    env_file: .env.jibri
    container_name: jitsi-jibri-${i}
    volumes:
      - \${CONFIG}/jibri-${i}:/config:Z
      - ./recordings:/recordings:Z
    environment:
      - JIBRI_INSTANCE_ID=${i}
    depends_on:
      - jicofo
    networks:
      meet.jitsi:

EOS
done

echo "Generated ${OUTPUT} with ${COUNT} jibri services"

echo "Creating new jibri containers and removing orphans..."
docker compose -f "${SCRIPT_DIR}/docker-compose.yml" -f "${OUTPUT}" up -d --remove-orphans 2>&1

echo "Restarting autoscaler with updated config..."
docker compose -f "${SCRIPT_DIR}/docker-compose.yml" -f "${OUTPUT}" up -d --force-recreate jibri-autoscaler 2>&1

echo "Done."
